site_name: Tesauro AI Governance
site_description: Tesauro bilingue (EN/IT) sulla governance dell’IA
repo_url: https://github.com/mauritiuss/tesauro-ai
edit_uri: edit/main/docs/
theme:
  name: mkdocs
plugins:
  - search
nav:
  - Home: index.md
  - Termini:
      - Indice: terms/index.md
  - Mockup: mockup.md