name: Deploy MkDocs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - name: Genera pagine dal JSON
        run: python scripts/generate_docs.py
      - name: Pubblica su GitHub Pages (branch gh-pages)
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
